spring.datasource.url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username: root
spring.datasource.password: test
spring.jpa.hibernate.ddl-auto: create
parametrTest:
  value: 55555
